### PR TITLE
Convert to new smart pointers to fix build errors with libpointmatcher 1.3.1

### PR DESCRIPTION
**Pull request by jsburklund**
Required update to smart pointers with the new libpointmatcher 1.3.1 version.

### CODE REVIEW

**Comment by YoshuaNava** [comment]
Thank you!

Out of scope observation: I think we should change all shared_ptr instances in these file for unique_ptr, which have less overhead computationally.

**Comment by jsburklund** [comment]
There are other sections of the code in point_cloud.cpp that should also be updated to use smart pointers. This is not required for the libpointmatcher update, since the pointers remain within scope.

**Comment by jsburklund** [comment]
> Thank you!
> 
> Out of scope observation: I think we should change all shared_ptr instances in this file for unique_ptr, which have less overhead computationally. I would do this in a different PR.

shared_ptr is required in this case, since this is part of the interface from libpointmatcher, and a shared_ptr cannot be converted to a unique_ptr.  In general though, yes a unique_ptr is preferred.

**Comment by remod** [comment]
@YoshuaNava I think Jordan cannot merge PRs, please do so if everything looks good.

**Comment by jsburklund** [comment]
> @YoshuaNava I think Jordan cannot merge PRs, please do so if everything looks good.

I cannot merge pull requests. This is also tied to the PR to update libpointmatcher to 1.3.0, and I don't think that this can be merged in without corresponding update without causing runtime issues.

**Comment by jsburklund** [comment]
Ready to merge. Needs to be synchronized with libpointmatcher update to 1.3.1

**Pull request merged**
