### PR TITLE
Use shared_ptr for boundingBoxFilter

### PR DESCRIPTION
**Pull request by jinkunw**

### CODE REVIEW

**Comment by YoshuaNava** [comment]
Hi @jinkunw,
Thank you for your contribution.

I would first like to ask you about your motivation behind these changes? By looking at your code I understand that you seek to automate deletion of the BoundingBoxFilter after it has gone out of scope. 

@remod what do you think of this approach? It abstracts the lifecycle of the BoundingBoxFlter, but might also add some overhead.



Regards,
Yoshua

**Comment by jinkunw** [comment]
Hi @YoshuaNava, it's because I got compilation error with the latest code of `libpointmatcher`.

```
/home/jinkun/Documents/exploration_ws/src/pointmatcher_ros/pointmatcher_ros/src/StampedPointCloud.cpp: In member function ‘bool PointMatcher_ros::StampedPointCloud::filterByBoundingBox(float, float, float, float, float, float, bool)’:
/home/jinkun/Documents/exploration_ws/src/pointmatcher_ros/pointmatcher_ros/src/StampedPointCloud.cpp:181:99: error: cannot convert ‘std::shared_ptr<PointMatcher<float>::DataPointsFilter>’ to ‘PointMatcher_ros::PmPointCloudFilter* {aka PointMatcher<float>::DataPointsFilter*}’ in initialization
                                       {"removeInside", PointMatcherSupport::toParam(!keepInside)}});
```

**Comment by remod** [comment]
@jinkunw We use a fork of libpointmatcher which is updated from time to time, please have a look at https://github.com/ANYbotics/pointmatcher-ros

**Comment by jinkunw** [comment]
Thanks for adding it in the README! i will close the pull request.

**Pull request closed without merging**
